# ui/login/Login
The_username_and/or_password_you_supplied_were_not_recognised.=Utilisateur et/ou mot de passe erron\u00E9.
# ui/main/Main
# ui/login/Login
Exit=&Quitter
# ui/login/Login
# bo/Users
Password=Mot de passe :
# ui/login/Login
Invalid_Password=Mot de passe invalide
# ui/login/Login
# ui/internet/Pets911Settings
Username=Utilisateur :
# utility/Utils
# ui/users/UserView
# ui/ui/Dialog
# ui/ui/DBFSBrowser
# ui/owner/VoucherEdit
# ui/main/Main
# ui/animal/MediaSelector
# ui/animal/DietEdit
# ui/animal/VaccinationView
# ui/animal/VaccinationEdit
# ui/animal/VaccinationSelector
# ui/animal/MediaEdit
# ui/animal/MediaAdd
# ui/login/Login
# ui/movement/MovementSelector
# ui/movement/MovementView
# reports/DiaryNotesToday
# reports/Report
# reports/MedicalDiary
# reports/VaccinationDiary
# reports/Vets
# internet/Publisher
# mailmerge/MailMerge
# wordprocessor/MovementDocument
# wordprocessor/OwnerDonationDocument
Error=Erreur
# ui/splash/About
Version_=Version 
# ui/login/Login
Login=Ok
# ui/login/Login
An_error_occurred_obtaining_a_connection_to_the_database_-_=Une erreur est survenue durant la connexion \u00E0 la base de donn\u00E9es - 
# ui/login/Login
Animal_Shelter_Manager_Login=Animal Shelter Manager - Authentification
# ui/login/Login
default_username_password_hint=L'utilisateur par d\u00E9faut est "user" avec le mot de passe "letmein"
